server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/selfcheckout
    username: ${USER}
    password: ""
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
